name: PeaceKeeper
main: com.incapable.peacekeeper.Main
version: 1.2.3
description: Custom chat monitoring and spam protection
website: http://infinitasoftware.nl
authors: [incapable1337]
commands:
  pk:
    description: Shows all PeaceKeeper Commands
    permission: peacekeeper.pk
    usage: /pk
    aliases: [peacekeeper, pkeeper]
  punish:
    description: Punishes player
    permission: peacekeeper.punish
    usage: /punish player
  addbadword:
    description: Adds bad words to list
    permission: peacekeeper.addbadword
    usage: /<command> <word> [word] [word]
  setconfig:
    description: Sets a config variable
    permission: peacekeeper.setconfig
    usage: /<command> <parameter> <value>
  getconfig:
    description: Gets the complete current config
    permission: peacekeeper.getconfig
    usage: /<command>
  unban:
    description: Unbans a player
    permission: peacekeeper.unban
    usage: /<command> <parameter>
permissions:
   peacekeeper.*:
      default: op